steps:
- name: 'maven:3.9.6-eclipse-temurin-11'
  entrypoint: 'mvn'
  args: ['test']
  
- name: 'gcr.io/cloud-builders/docker'
  args:
    [
      'build',
      '-t',
      'australia-southeast1-docker.pkg.dev/$PROJECT_ID/calculator-repo/calculator-app',
      '.'
    ]

- name: 'gcr.io/cloud-builders/docker'
  args:
	[
	  'push',
	  'australia-southeast1-docker.pkg.dev/$PROJECT_ID/calculator-repo/calculator-app'
	]

images:
- 'australia-southeast1-docker.pkg.dev/$PROJECT_ID/calculator-repo/calculator-app'


options:
  logging: CLOUD_LOGGING_ONLY